---
- name: Prep all nodes for Kuberneted
  hosts: k8s
  become: true
  roles: [common]

- name: Bootstrap the first control plane
  hosts: primary_cp
  become: true
  roles: [control_plane]

- name: Set up kube-vip on the first control plane
  hosts: primary_cp
  become: true
  roles: [kube_vip]